# @package _global_

defaults:
  - _self_
  - data: animateface # choose datamodule with `test_dataloader()` for evaluation
  - model: diffusion
  - logger: wandb
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["dev"]

# passing checkpoint path is necessary for evaluation
ckpt_path: logs/train/runs/2024-04-25_13-31-24/checkpoints/epoch_000.ckpt
